const bet = {
  "success": true,
  "accessToken": "00cb15d5-17bf-4eaa-b1cf-efe89cc9466d",
  "content": [{
      "sortNo": 4,
      "code": "gyjh",
      "odds": [{
          "minOdds": "4.98",
          "playCode": "gyjh",
          "flag": 0,
          "code": "gyjhda",
          "maxOdds": "4.98",
          "rakeback": "-4.5",
          "numName": "大",
          "lotVersion": 2,
          "id": 38710,
          "lotType": 3
      }, {
          "minOdds": "4.98",
          "playCode": "gyjh",
          "flag": 0,
          "code": "gyjhx",
          "maxOdds": "4.98",
          "rakeback": "-4.5",
          "numName": "小",
          "lotVersion": 2,
          "id": 38711,
          "lotType": 3
      }, {
          "minOdds": "4.98",
          "playCode": "gyjh",
          "flag": 0,
          "code": "gyjhd",
          "maxOdds": "4.98",
          "rakeback": "-4.5",
          "numName": "单",
          "lotVersion": 2,
          "id": 38712,
          "lotType": 3
      }, {
          "minOdds": "4.98",
          "playCode": "gyjh",
          "flag": 0,
          "code": "gyjhs",
          "maxOdds": "4.98",
          "rakeback": "-4.5",
          "numName": "双",
          "lotVersion": 2,
          "id": 38713,
          "lotType": 3
      }],
      "name": "冠，亚和"
  }, {
      "sortNo": 8,
      "code": "gj",
      "odds": [{
          "minOdds": "1.8",
          "playCode": "gj",
          "flag": 0,
          "code": "gjda",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "大",
          "lotVersion": 2,
          "id": 38714,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "gj",
          "flag": 0,
          "code": "gjx",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "小",
          "lotVersion": 2,
          "id": 38715,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "gj",
          "flag": 0,
          "code": "gjd",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "单",
          "lotVersion": 2,
          "id": 38716,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "gj",
          "flag": 0,
          "code": "gjs",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "双",
          "lotVersion": 2,
          "id": 38717,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "gj",
          "flag": 0,
          "code": "gjl",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "1V10龙",
          "lotVersion": 2,
          "id": 38718,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "gj",
          "flag": 0,
          "code": "gjh",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "1V10虎",
          "lotVersion": 2,
          "id": 38719,
          "lotType": 3
      }],
      "name": "冠军"
  }, {
      "sortNo": 8,
      "code": "yj",
      "odds": [{
          "minOdds": "1.95",
          "playCode": "yj",
          "flag": 0,
          "code": "yjda",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "大",
          "lotVersion": 2,
          "id": 38720,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "yj",
          "flag": 0,
          "code": "yjx",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "小",
          "lotVersion": 2,
          "id": 38721,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "yj",
          "flag": 0,
          "code": "yjd",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "单",
          "lotVersion": 2,
          "id": 38722,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "yj",
          "flag": 0,
          "code": "yjs",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "双",
          "lotVersion": 2,
          "id": 38723,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "yj",
          "flag": 0,
          "code": "yjl",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "2V9龙",
          "lotVersion": 2,
          "id": 38724,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "yj",
          "flag": 0,
          "code": "yjh",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "2V9虎",
          "lotVersion": 2,
          "id": 38725,
          "lotType": 3
      }],
      "name": "亚军"
  }, {
      "sortNo": 8,
      "code": "dsm",
      "odds": [{
          "minOdds": "1.95",
          "playCode": "dsm",
          "flag": 0,
          "code": "dsmda",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "大",
          "lotVersion": 2,
          "id": 38726,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dsm",
          "flag": 0,
          "code": "dsmx",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "小",
          "lotVersion": 2,
          "id": 38727,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dsm",
          "flag": 0,
          "code": "dsmd",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "单",
          "lotVersion": 2,
          "id": 38728,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dsm",
          "flag": 0,
          "code": "dsms",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "双",
          "lotVersion": 2,
          "id": 38729,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dsm",
          "flag": 0,
          "code": "dsml",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "3V8龙",
          "lotVersion": 2,
          "id": 38730,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dsm",
          "flag": 0,
          "code": "dsmh",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "3V8虎",
          "lotVersion": 2,
          "id": 38731,
          "lotType": 3
      }],
      "name": "第三名"
  }, {
      "sortNo": 8,
      "code": "dsim",
      "odds": [{
          "minOdds": "1.95",
          "playCode": "dsim",
          "flag": 0,
          "code": "dsimda",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "大",
          "lotVersion": 2,
          "id": 38732,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dsim",
          "flag": 0,
          "code": "dsimx",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "小",
          "lotVersion": 2,
          "id": 38733,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dsim",
          "flag": 0,
          "code": "dsimd",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "单",
          "lotVersion": 2,
          "id": 38734,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dsim",
          "flag": 0,
          "code": "dsims",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "双",
          "lotVersion": 2,
          "id": 38735,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dsim",
          "flag": 0,
          "code": "dsiml",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "4V7龙",
          "lotVersion": 2,
          "id": 38736,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dsim",
          "flag": 0,
          "code": "dsimh",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "4V7虎",
          "lotVersion": 2,
          "id": 38737,
          "lotType": 3
      }],
      "name": "第四名"
  }, {
      "sortNo": 8,
      "code": "dwm",
      "odds": [{
          "minOdds": "1.8",
          "playCode": "dwm",
          "flag": 0,
          "code": "dwmda",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "大",
          "lotVersion": 2,
          "id": 38738,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dwm",
          "flag": 0,
          "code": "dwmx",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "小",
          "lotVersion": 2,
          "id": 38739,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dwm",
          "flag": 0,
          "code": "dwmd",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "单",
          "lotVersion": 2,
          "id": 38740,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dwm",
          "flag": 0,
          "code": "dwms",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "双",
          "lotVersion": 2,
          "id": 38741,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dwm",
          "flag": 0,
          "code": "dwml",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "5V6龙",
          "lotVersion": 2,
          "id": 38742,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dwm",
          "flag": 0,
          "code": "dwmh",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "5V6虎",
          "lotVersion": 2,
          "id": 38743,
          "lotType": 3
      }],
      "name": "第五名"
  }, {
      "sortNo": 8,
      "code": "dlm",
      "odds": [{
          "minOdds": "1.8",
          "playCode": "dlm",
          "flag": 0,
          "code": "dlmda",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "大",
          "lotVersion": 2,
          "id": 38744,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dlm",
          "flag": 0,
          "code": "dlmx",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "小",
          "lotVersion": 2,
          "id": 38745,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dlm",
          "flag": 0,
          "code": "dlmd",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "单",
          "lotVersion": 2,
          "id": 38746,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dlm",
          "flag": 0,
          "code": "dlms",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "双",
          "lotVersion": 2,
          "id": 38747,
          "lotType": 3
      }],
      "name": "第六名"
  }, {
      "sortNo": 8,
      "code": "dqm",
      "odds": [{
          "minOdds": "1.8",
          "playCode": "dqm",
          "flag": 0,
          "code": "dqmda",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "大",
          "lotVersion": 2,
          "id": 38748,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dqm",
          "flag": 0,
          "code": "dqmx",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "小",
          "lotVersion": 2,
          "id": 38749,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dqm",
          "flag": 0,
          "code": "dqmd",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "单",
          "lotVersion": 2,
          "id": 38750,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dqm",
          "flag": 0,
          "code": "dqms",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "双",
          "lotVersion": 2,
          "id": 38751,
          "lotType": 3
      }],
      "name": "第七名"
  }, {
      "sortNo": 8,
      "code": "dbm",
      "odds": [{
          "minOdds": "1.8",
          "playCode": "dbm",
          "flag": 0,
          "code": "dbmda",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "大",
          "lotVersion": 2,
          "id": 38752,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dbm",
          "flag": 0,
          "code": "dbmx",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "小",
          "lotVersion": 2,
          "id": 38753,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dbm",
          "flag": 0,
          "code": "dbmd",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "单",
          "lotVersion": 2,
          "id": 38754,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "dbm",
          "flag": 0,
          "code": "dbms",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "双",
          "lotVersion": 2,
          "id": 38755,
          "lotType": 3
      }],
      "name": "第八名"
  }, {
      "sortNo": 8,
      "code": "djm",
      "odds": [{
          "minOdds": "1.8",
          "playCode": "djm",
          "flag": 0,
          "code": "djmda",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "大",
          "lotVersion": 2,
          "id": 38756,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "djm",
          "flag": 0,
          "code": "djmx",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "小",
          "lotVersion": 2,
          "id": 38757,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "djm",
          "flag": 0,
          "code": "djmd",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "单",
          "lotVersion": 2,
          "id": 38758,
          "lotType": 3
      }, {
          "minOdds": "1.8",
          "playCode": "djm",
          "flag": 0,
          "code": "djms",
          "maxOdds": "1.84",
          "rakeback": "2",
          "numName": "双",
          "lotVersion": 2,
          "id": 38759,
          "lotType": 3
      }],
      "name": "第九名"
  }, {
      "sortNo": 8,
      "code": "dshm",
      "odds": [{
          "minOdds": "1.95",
          "playCode": "dshm",
          "flag": 0,
          "code": "dshmda",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "大",
          "lotVersion": 2,
          "id": 38760,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dshm",
          "flag": 0,
          "code": "dshmx",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "小",
          "lotVersion": 2,
          "id": 38761,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dshm",
          "flag": 0,
          "code": "dshmd",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "单",
          "lotVersion": 2,
          "id": 38762,
          "lotType": 3
      }, {
          "minOdds": "1.95",
          "playCode": "dshm",
          "flag": 0,
          "code": "dshms",
          "maxOdds": "1.95",
          "rakeback": "-5.5",
          "numName": "双",
          "lotVersion": 2,
          "id": 38763,
          "lotType": 3
      }],
      "name": "第十名"
  }]
};

export { bet }