export const api = {
  AccountDetail: "UserService/AccountDetail/Search",
  AdvertisingClassification: "UserService/AdvertisingClassification/Search",
  Advertising: "UserService/Advertising/Search",
  AgencyInfo: "UserService/AgencyInfo/Search",
  AgencyMember: "UserService/AgencyMember/Search",
  AgencyReport: "UserService/AgencyReport/Search",
  ArticleInfo: "UserService/ArticleInfo/Search",
  BetOrder: "UserService/BetOrder/Search",
  LotteryInfo: "UserService/LotteryInfo/Search",
  LotteryPlaying: "UserService/LotteryPlaying/Search",
  LotteryReport: "UserService/LotteryReport/Search",
  Login: "UserService/User/Login",
  Register: "UserService/User/Register",
  UserBetReport: "UserService/UserBetReport/Search",
  UserClassification: "UserService/UserClassification/Search",
  UserInfo: "UserService/UserInfo/Search",
  AccountInfo: "UserService/AccountInfo/Search",
};
